GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/61013429120aaf43b4d151a3

###
DELETE http://localhost:3001/api/persons/610151a1984967009404a826

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "",
    "number": "45"
}

###
PUT http://localhost:3001/api/persons/610147d9c34171359416cad0 HTTP/1.1
content-type: application/json

{
    "name": "",
    "number": "1234"
}