GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/6101657b0f41b600150e9b67

###
DELETE http://localhost:3001/api/persons/610151a1984967009404a826

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "olli",
    "number": "13980235"
}

###
PUT http://localhost:3001/api/persons/6101657b0f41b600150e9b67 HTTP/1.1
content-type: application/json

{
    "name": "olli",
    "number": "565"
}